version: '3'
services:
  primary:
    image: bind
    ports:
      - 145.100.104.117:53:53/tcp
      - 145.100.104.117:53:53/udp
    volume:
      - $PWD/primary.zone.conf:/usr/local/etc/bind/myzone.conf:ro
  secondary:
    image: bind
    ports:
      - 145.100.111.10:53:53/tcp
      - 145.100.111.10:53:53/udp
      - 145.100.104.117:53:53/udp
    volume:
      - $PWD/secondary.zone.conf:/usr/local/etc/bind/myzone.conf:ro

